### ISSUE TITLE
弹出窗口

### ISSUE THREAD

**Issue by Edfgdz** [by-syk/PathCopier#1]
软件还能更一下吗？想把这个弹出窗口去掉,觉得不需要这个来提醒复制成功
![1516688942614](https://user-images.githubusercontent.com/26460124/35261310-873954c0-004a-11e8-9199-fc508f1523b8.jpg)

**Comment by by-syk** [comment]
不会。弹窗显示结果（成功或失败），且会自动关闭，也可点击对话框外迅速关闭
